import Foundation
import SwiftUI

class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()
    
    @Published var currentLanguage: SupportedLanguage = .german {
        didSet {
            UserDefaults.standard.set(currentLanguage.rawValue, forKey: "selectedLanguage")
        }
    }
    
    enum SupportedLanguage: String, CaseIterable {
        case german = "de"
        case english = "en"
        case spanish = "es"
        case french = "fr"
        case italian = "it"
        case portuguese = "pt"
        case dutch = "nl"
        case russian = "ru"
        case chinese = "zh"
        case japanese = "ja"
        case korean = "ko"
        case arabic = "ar"
        
        var displayName: String {
            switch self {
            case .german: return "Deutsch"
            case .english: return "English"
            case .spanish: return "Español"
            case .french: return "Français"
            case .italian: return "Italiano"
            case .portuguese: return "Português"
            case .dutch: return "Nederlands"
            case .russian: return "Русский"
            case .chinese: return "中文"
            case .japanese: return "日本語"
            case .korean: return "한국어"
            case .arabic: return "العربية"
            }
        }
    }
    
    private init() {
        if let savedLanguage = UserDefaults.standard.string(forKey: "selectedLanguage"),
           let language = SupportedLanguage(rawValue: savedLanguage) {
            currentLanguage = language
        }
    }
    
    func localizedString(_ key: LocalizationKey) -> String {
        return translations[currentLanguage]?[key] ?? translations[.english]?[key] ?? key.rawValue
    }
    
    // MARK: - Translations Dictionary
    private let translations: [SupportedLanguage: [LocalizationKey: String]] = [
        .german: [
            .appName: "ShotCast",
            .menuOpen: "ShotCast öffnen",
            .menuSettings: "Einstellungen...",
            .menuQuit: "Beenden",
            .settingsTitle: "ShotCast Einstellungen",
            .settingsGeneral: "Allgemein",
            .settingsAppearance: "Aussehen",
            .settingsAdvanced: "Erweitert",
            .settingsLanguage: "Sprache",
            .settingsTheme: "Thema",
            .settingsMaxItems: "Maximale Anzahl Items",
            .settingsBarHeight: "Balkenhöhe",
            .settingsBarOpacity: "Transparenz",
            .settingsCornerRadius: "Eckenradius",
            .settingsItemSpacing: "Elementabstand",
            .settingsAutoShow: "Automatisch anzeigen",
            .settingsLaunchAtLogin: "Bei Anmeldung starten",
            .themeSystem: "System",
            .themeLight: "Hell",
            .themeDark: "Dunkel",
            .copied: "Kopiert!",
            .copyText: "Text wurde in die Zwischenablage kopiert",
            .emptyClipboard: "Keine Inhalte im Clipboard",
            .contextCopy: "Kopieren",
            .contextFavorite: "Zu Favoriten",
            .contextUnfavorite: "Aus Favoriten",
            .contextSaveAsFile: "Als Datei speichern...",
            .contextDelete: "Löschen",
            .ocrExtract: "Text per OCR extrahieren",
            .ocrSuccess: "OCR Text extrahiert",
            .fileTypeImage: "Bild",
            .fileTypeText: "Text",
            .fileTypeDocument: "Dokument",
            .fileTypePDF: "PDF",
            .fileTypeVideo: "Video",
            .fileTypeAudio: "Audio",
            .fileTypeArchive: "Archiv",
            .fileTypeURL: "URL",
            .fileTypeCode: "Code",
            .fileTypeOther: "Datei",
            .helpSettings: "ShotCast Einstellungen",
            .helpClose: "ShotCast schließen",
            .settingsBehavior: "Verhalten",
            .settingsBehaviorDescription: "Verhalten der App anpassen",
            .settingsAutoShowDescription: "Die App wird automatisch angezeigt, wenn etwas kopiert wird",
            .settingsLaunchAtLoginDescription: "ShotCast wird automatisch beim Anmelden gestartet",
            .settingsAutoHide: "Automatisch ausblenden",
            .settingsAutoHideDescription: "Die App wird nach einer bestimmten Zeit automatisch ausgeblendet",
            .settingsHideDelay: "Ausblende-Verzögerung",
            .settingsResetDefaults: "Auf Standard zurücksetzen",
            .itemLimitTen: "Letzte 10 Shots",
            .itemLimitHundred: "Letzte 100 Shots",
            .itemLimitUnlimited: "Unbegrenzt",
            .sourceLabel: "Quelle",
            .ocrFast: "Schnell",
            .ocrBalanced: "Ausgewogen",
            .ocrAccurate: "Genau",
            .ocrError: "OCR Fehler",
            .ocrInvalidImage: "Ungültiges Bild",
            .ocrNoTextFound: "Kein Text gefunden",
            .ocrCancelled: "OCR abgebrochen"
        ],
        .english: [
            .appName: "ShotCast",
            .menuOpen: "Open ShotCast",
            .menuSettings: "Settings...",
            .menuQuit: "Quit",
            .settingsTitle: "ShotCast Settings",
            .settingsGeneral: "General",
            .settingsAppearance: "Appearance",
            .settingsAdvanced: "Advanced",
            .settingsLanguage: "Language",
            .settingsTheme: "Theme",
            .settingsMaxItems: "Maximum Items",
            .settingsBarHeight: "Bar Height",
            .settingsBarOpacity: "Opacity",
            .settingsCornerRadius: "Corner Radius",
            .settingsItemSpacing: "Item Spacing",
            .settingsAutoShow: "Auto Show",
            .settingsLaunchAtLogin: "Launch at Login",
            .themeSystem: "System",
            .themeLight: "Light",
            .themeDark: "Dark",
            .copied: "Copied!",
            .copyText: "Text copied to clipboard",
            .emptyClipboard: "No content in clipboard",
            .contextCopy: "Copy",
            .contextFavorite: "Add to Favorites",
            .contextUnfavorite: "Remove from Favorites",
            .contextSaveAsFile: "Save as File...",
            .contextDelete: "Delete",
            .ocrExtract: "Extract text with OCR",
            .ocrSuccess: "OCR text extracted",
            .fileTypeImage: "Image",
            .fileTypeText: "Text",
            .fileTypeDocument: "Document",
            .fileTypePDF: "PDF",
            .fileTypeVideo: "Video",
            .fileTypeAudio: "Audio",
            .fileTypeArchive: "Archive",
            .fileTypeURL: "URL",
            .fileTypeCode: "Code",
            .fileTypeOther: "File",
            .helpSettings: "ShotCast Settings",
            .helpClose: "Close ShotCast",
            .settingsBehavior: "Behavior",
            .settingsBehaviorDescription: "Customize app behavior",
            .settingsAutoShowDescription: "The app will automatically show when something is copied",
            .settingsLaunchAtLoginDescription: "ShotCast will automatically start when logging in",
            .settingsAutoHide: "Auto Hide",
            .settingsAutoHideDescription: "The app will automatically hide after a certain time",
            .settingsHideDelay: "Hide Delay",
            .settingsResetDefaults: "Reset to Defaults",
            .itemLimitTen: "Last 10 Shots",
            .itemLimitHundred: "Last 100 Shots",
            .itemLimitUnlimited: "Unlimited",
            .sourceLabel: "Source",
            .ocrFast: "Fast",
            .ocrBalanced: "Balanced",
            .ocrAccurate: "Accurate",
            .ocrError: "OCR Error",
            .ocrInvalidImage: "Invalid Image",
            .ocrNoTextFound: "No Text Found",
            .ocrCancelled: "OCR Cancelled"
        ],
        .spanish: [
            .appName: "ShotCast",
            .menuOpen: "Abrir ShotCast",
            .menuSettings: "Configuración...",
            .menuQuit: "Salir",
            .settingsTitle: "Configuración de ShotCast",
            .settingsGeneral: "General",
            .settingsAppearance: "Apariencia",
            .settingsAdvanced: "Avanzado",
            .settingsLanguage: "Idioma",
            .settingsTheme: "Tema",
            .settingsMaxItems: "Elementos Máximos",
            .settingsBarHeight: "Altura de Barra",
            .settingsBarOpacity: "Opacidad",
            .settingsCornerRadius: "Radio de Esquina",
            .settingsItemSpacing: "Espaciado de Elementos",
            .settingsAutoShow: "Mostrar Automáticamente",
            .settingsLaunchAtLogin: "Iniciar al Iniciar Sesión",
            .themeSystem: "Sistema",
            .themeLight: "Claro",
            .themeDark: "Oscuro",
            .copied: "¡Copiado!",
            .copyText: "Texto copiado al portapapeles",
            .emptyClipboard: "Sin contenido en portapapeles",
            .contextCopy: "Copiar",
            .contextFavorite: "Añadir a Favoritos",
            .contextUnfavorite: "Quitar de Favoritos",
            .contextSaveAsFile: "Guardar como Archivo...",
            .contextDelete: "Eliminar",
            .ocrExtract: "Extraer texto con OCR",
            .ocrSuccess: "Texto OCR extraído",
            .fileTypeImage: "Imagen",
            .fileTypeText: "Texto",
            .fileTypeDocument: "Documento",
            .fileTypePDF: "PDF",
            .fileTypeVideo: "Video",
            .fileTypeAudio: "Audio",
            .fileTypeArchive: "Archivo",
            .fileTypeURL: "URL",
            .fileTypeCode: "Código",
            .fileTypeOther: "Archivo",
            .helpSettings: "Configuración de ShotCast",
            .helpClose: "Cerrar ShotCast",
            .settingsBehavior: "Comportamiento",
            .settingsBehaviorDescription: "Personalizar comportamiento de la app",
            .settingsAutoShowDescription: "La app se mostrará automáticamente cuando se copie algo",
            .settingsLaunchAtLoginDescription: "ShotCast se iniciará automáticamente al iniciar sesión",
            .settingsAutoHide: "Ocultar Automáticamente",
            .settingsAutoHideDescription: "La app se ocultará automáticamente después de cierto tiempo",
            .settingsHideDelay: "Retraso de Ocultación",
            .settingsResetDefaults: "Restablecer Valores Predeterminados",
            .itemLimitTen: "Últimos 10 Disparos",
            .itemLimitHundred: "Últimos 100 Disparos",
            .itemLimitUnlimited: "Ilimitado",
            .sourceLabel: "Fuente",
            .ocrFast: "Rápido",
            .ocrBalanced: "Equilibrado",
            .ocrAccurate: "Preciso",
            .ocrError: "Error OCR",
            .ocrInvalidImage: "Imagen Inválida",
            .ocrNoTextFound: "No se Encontró Texto",
            .ocrCancelled: "OCR Cancelado"
        ],
        .french: [
            .appName: "ShotCast",
            .menuOpen: "Ouvrir ShotCast",
            .menuSettings: "Réglages...",
            .menuQuit: "Quitter",
            .settingsTitle: "Réglages ShotCast",
            .settingsGeneral: "Général",
            .settingsAppearance: "Apparence",
            .settingsAdvanced: "Avancé",
            .settingsLanguage: "Langue",
            .settingsTheme: "Thème",
            .settingsMaxItems: "Éléments Maximum",
            .settingsBarHeight: "Hauteur de Barre",
            .settingsBarOpacity: "Opacité",
            .settingsCornerRadius: "Rayon des Coins",
            .settingsItemSpacing: "Espacement des Éléments",
            .settingsAutoShow: "Affichage Automatique",
            .settingsLaunchAtLogin: "Lancer à l'Ouverture",
            .themeSystem: "Système",
            .themeLight: "Clair",
            .themeDark: "Sombre",
            .copied: "Copié !",
            .copyText: "Texte copié dans le presse-papiers",
            .emptyClipboard: "Aucun contenu dans le presse-papiers",
            .contextCopy: "Copier",
            .contextFavorite: "Ajouter aux Favoris",
            .contextUnfavorite: "Retirer des Favoris",
            .contextSaveAsFile: "Enregistrer comme Fichier...",
            .contextDelete: "Supprimer",
            .ocrExtract: "Extraire texte avec OCR",
            .ocrSuccess: "Texte OCR extrait",
            .fileTypeImage: "Image",
            .fileTypeText: "Texte",
            .fileTypeDocument: "Document",
            .fileTypePDF: "PDF",
            .fileTypeVideo: "Vidéo",
            .fileTypeAudio: "Audio",
            .fileTypeArchive: "Archive",
            .fileTypeURL: "URL",
            .fileTypeCode: "Code",
            .fileTypeOther: "Fichier",
            .helpSettings: "Réglages ShotCast",
            .helpClose: "Fermer ShotCast",
            .settingsBehavior: "Comportement",
            .settingsBehaviorDescription: "Personnaliser le comportement de l'app",
            .settingsAutoShowDescription: "L'app s'affichera automatiquement quand quelque chose est copié",
            .settingsLaunchAtLoginDescription: "ShotCast se lancera automatiquement à l'ouverture",
            .settingsAutoHide: "Masquage Automatique",
            .settingsAutoHideDescription: "L'app se masquera automatiquement après un certain temps",
            .settingsHideDelay: "Délai de Masquage",
            .settingsResetDefaults: "Rétablir les Valeurs par Défaut",
            .itemLimitTen: "10 Derniers Captures",
            .itemLimitHundred: "100 Derniers Captures",
            .itemLimitUnlimited: "Illimité",
            .sourceLabel: "Source",
            .ocrFast: "Rapide",
            .ocrBalanced: "Équilibré",
            .ocrAccurate: "Précis",
            .ocrError: "Erreur OCR",
            .ocrInvalidImage: "Image Invalide",
            .ocrNoTextFound: "Aucun Texte Trouvé",
            .ocrCancelled: "OCR Annulé"
        ],
        .italian: [
            .appName: "ShotCast",
            .menuOpen: "Apri ShotCast",
            .menuSettings: "Impostazioni...",
            .menuQuit: "Esci",
            .settingsTitle: "Impostazioni ShotCast",
            .settingsGeneral: "Generale",
            .settingsAppearance: "Aspetto",
            .settingsAdvanced: "Avanzate",
            .settingsLanguage: "Lingua",
            .settingsTheme: "Tema",
            .settingsMaxItems: "Elementi Massimi",
            .settingsBarHeight: "Altezza Barra",
            .settingsBarOpacity: "Opacità",
            .settingsCornerRadius: "Raggio Angoli",
            .settingsItemSpacing: "Spaziatura Elementi",
            .settingsAutoShow: "Mostra Automaticamente",
            .settingsLaunchAtLogin: "Avvia all'Accesso",
            .themeSystem: "Sistema",
            .themeLight: "Chiaro",
            .themeDark: "Scuro",
            .copied: "Copiato!",
            .copyText: "Testo copiato negli appunti",
            .emptyClipboard: "Nessun contenuto negli appunti",
            .contextCopy: "Copia",
            .contextFavorite: "Aggiungi ai Preferiti",
            .contextUnfavorite: "Rimuovi dai Preferiti",
            .contextSaveAsFile: "Salva come File...",
            .contextDelete: "Elimina",
            .ocrExtract: "Estrai testo con OCR",
            .ocrSuccess: "Testo OCR estratto",
            .fileTypeImage: "Immagine",
            .fileTypeText: "Testo",
            .fileTypeDocument: "Documento",
            .fileTypePDF: "PDF",
            .fileTypeVideo: "Video",
            .fileTypeAudio: "Audio",
            .fileTypeArchive: "Archivio",
            .fileTypeURL: "URL",
            .fileTypeCode: "Codice",
            .fileTypeOther: "File",
            .helpSettings: "Impostazioni ShotCast",
            .helpClose: "Chiudi ShotCast",
            .settingsBehavior: "Comportamento",
            .settingsBehaviorDescription: "Personalizzare comportamento dell'app",
            .settingsAutoShowDescription: "L'app si mostrerà automaticamente quando qualcosa viene copiato",
            .settingsLaunchAtLoginDescription: "ShotCast si avvierà automaticamente all'accesso",
            .settingsAutoHide: "Nascondere Automaticamente",
            .settingsAutoHideDescription: "L'app si nasconderà automaticamente dopo un certo tempo",
            .settingsHideDelay: "Ritardo di Nascondimento",
            .settingsResetDefaults: "Ripristina Impostazioni Predefinite",
            .itemLimitTen: "Ultimi 10 Scatti",
            .itemLimitHundred: "Ultimi 100 Scatti",
            .itemLimitUnlimited: "Illimitato",
            .sourceLabel: "Fonte",
            .ocrFast: "Veloce",
            .ocrBalanced: "Equilibrato",
            .ocrAccurate: "Preciso",
            .ocrError: "Errore OCR",
            .ocrInvalidImage: "Immagine Non Valida",
            .ocrNoTextFound: "Nessun Testo Trovato",
            .ocrCancelled: "OCR Annullato"
        ],
        .portuguese: [
            .appName: "ShotCast",
            .menuOpen: "Abrir ShotCast",
            .menuSettings: "Configurações...",
            .menuQuit: "Sair",
            .settingsTitle: "Configurações do ShotCast",
            .settingsGeneral: "Geral",
            .settingsAppearance: "Aparência",
            .settingsAdvanced: "Avançado",
            .settingsLanguage: "Idioma",
            .settingsTheme: "Tema",
            .settingsMaxItems: "Itens Máximos",
            .settingsBarHeight: "Altura da Barra",
            .settingsBarOpacity: "Opacidade",
            .settingsCornerRadius: "Raio das Bordas",
            .settingsItemSpacing: "Espaçamento de Itens",
            .settingsAutoShow: "Mostrar Automaticamente",
            .settingsLaunchAtLogin: "Iniciar no Login",
            .themeSystem: "Sistema",
            .themeLight: "Claro",
            .themeDark: "Escuro",
            .copied: "Copiado!",
            .copyText: "Texto copiado para área de transferência",
            .emptyClipboard: "Sem conteúdo na área de transferência",
            .contextCopy: "Copiar",
            .contextFavorite: "Adicionar aos Favoritos",
            .contextUnfavorite: "Remover dos Favoritos",
            .contextSaveAsFile: "Salvar como Arquivo...",
            .contextDelete: "Excluir",
            .ocrExtract: "Extrair texto com OCR",
            .ocrSuccess: "Texto OCR extraído",
            .fileTypeImage: "Imagem",
            .fileTypeText: "Texto",
            .fileTypeDocument: "Documento",
            .fileTypePDF: "PDF",
            .fileTypeVideo: "Vídeo",
            .fileTypeAudio: "Áudio",
            .fileTypeArchive: "Arquivo",
            .fileTypeURL: "URL",
            .fileTypeCode: "Código",
            .fileTypeOther: "Arquivo",
            .helpSettings: "Configurações do ShotCast",
            .helpClose: "Fechar ShotCast",
            .settingsBehavior: "Comportamento",
            .settingsBehaviorDescription: "Personalizar comportamento do app",
            .settingsAutoShowDescription: "O app será mostrado automaticamente quando algo for copiado",
            .settingsLaunchAtLoginDescription: "ShotCast iniciará automaticamente no login",
            .settingsAutoHide: "Ocultar Automaticamente",
            .settingsAutoHideDescription: "O app se ocultará automaticamente após um certo tempo",
            .settingsHideDelay: "Atraso de Ocultação",
            .settingsResetDefaults: "Redefinir para Padrões",
            .itemLimitTen: "Últimos 10 Disparos",
            .itemLimitHundred: "Últimos 100 Disparos",
            .itemLimitUnlimited: "Ilimitado",
            .sourceLabel: "Fonte",
            .ocrFast: "Rápido",
            .ocrBalanced: "Equilibrado",
            .ocrAccurate: "Preciso",
            .ocrError: "Erro OCR",
            .ocrInvalidImage: "Imagem Inválida",
            .ocrNoTextFound: "Nenhum Texto Encontrado",
            .ocrCancelled: "OCR Cancelado"
        ],
        .dutch: [
            .appName: "ShotCast",
            .menuOpen: "ShotCast Openen",
            .menuSettings: "Instellingen...",
            .menuQuit: "Afsluiten",
            .settingsTitle: "ShotCast Instellingen",
            .settingsGeneral: "Algemeen",
            .settingsAppearance: "Uiterlijk",
            .settingsAdvanced: "Geavanceerd",
            .settingsLanguage: "Taal",
            .settingsTheme: "Thema",
            .settingsMaxItems: "Maximum Items",
            .settingsBarHeight: "Balk Hoogte",
            .settingsBarOpacity: "Transparantie",
            .settingsCornerRadius: "Hoek Radius",
            .settingsItemSpacing: "Item Afstand",
            .settingsAutoShow: "Automatisch Tonen",
            .settingsLaunchAtLogin: "Starten bij Inloggen",
            .themeSystem: "Systeem",
            .themeLight: "Licht",
            .themeDark: "Donker",
            .copied: "Gekopieerd!",
            .copyText: "Tekst gekopieerd naar klembord",
            .emptyClipboard: "Geen inhoud in klembord",
            .contextCopy: "Kopiëren",
            .contextFavorite: "Aan Favorieten Toevoegen",
            .contextUnfavorite: "Uit Favorieten Verwijderen",
            .contextSaveAsFile: "Opslaan als Bestand...",
            .contextDelete: "Verwijderen",
            .ocrExtract: "Tekst extraheren met OCR",
            .ocrSuccess: "OCR tekst geëxtraheerd",
            .fileTypeImage: "Afbeelding",
            .fileTypeText: "Tekst",
            .fileTypeDocument: "Document",
            .fileTypePDF: "PDF",
            .fileTypeVideo: "Video",
            .fileTypeAudio: "Audio",
            .fileTypeArchive: "Archief",
            .fileTypeURL: "URL",
            .fileTypeCode: "Code",
            .fileTypeOther: "Bestand",
            .helpSettings: "ShotCast Instellingen",
            .helpClose: "ShotCast Sluiten",
            .settingsBehavior: "Gedrag",
            .settingsBehaviorDescription: "App-gedrag aanpassen",
            .settingsAutoShowDescription: "De app wordt automatisch getoond wanneer iets wordt gekopieerd",
            .settingsLaunchAtLoginDescription: "ShotCast wordt automatisch gestart bij inloggen",
            .settingsAutoHide: "Automatisch Verbergen",
            .settingsAutoHideDescription: "De app wordt automatisch verborgen na een bepaalde tijd",
            .settingsHideDelay: "Verberg Vertraging",
            .settingsResetDefaults: "Terugzetten naar Standaard",
            .itemLimitTen: "Laatste 10 Shots",
            .itemLimitHundred: "Laatste 100 Shots",
            .itemLimitUnlimited: "Onbeperkt",
            .sourceLabel: "Bron",
            .ocrFast: "Snel",
            .ocrBalanced: "Uitgebalanceerd",
            .ocrAccurate: "Nauwkeurig",
            .ocrError: "OCR Fout",
            .ocrInvalidImage: "Ongeldige Afbeelding",
            .ocrNoTextFound: "Geen Tekst Gevonden",
            .ocrCancelled: "OCR Geannuleerd"
        ],
        .russian: [
            .appName: "ShotCast",
            .menuOpen: "Открыть ShotCast",
            .menuSettings: "Настройки...",
            .menuQuit: "Выйти",
            .settingsTitle: "Настройки ShotCast",
            .settingsGeneral: "Общие",
            .settingsAppearance: "Внешний вид",
            .settingsAdvanced: "Дополнительно",
            .settingsLanguage: "Язык",
            .settingsTheme: "Тема",
            .settingsMaxItems: "Максимум элементов",
            .settingsBarHeight: "Высота панели",
            .settingsBarOpacity: "Прозрачность",
            .settingsCornerRadius: "Радиус углов",
            .settingsItemSpacing: "Расстояние между элементами",
            .settingsAutoShow: "Автопоказ",
            .settingsLaunchAtLogin: "Запускать при входе",
            .themeSystem: "Системная",
            .themeLight: "Светлая",
            .themeDark: "Тёмная",
            .copied: "Скопировано!",
            .copyText: "Текст скопирован в буфер обмена",
            .emptyClipboard: "Нет содержимого в буфере обмена",
            .contextCopy: "Копировать",
            .contextFavorite: "Добавить в избранное",
            .contextUnfavorite: "Удалить из избранного",
            .contextSaveAsFile: "Сохранить как файл...",
            .contextDelete: "Удалить",
            .ocrExtract: "Извлечь текст с помощью OCR",
            .ocrSuccess: "Текст OCR извлечён",
            .fileTypeImage: "Изображение",
            .fileTypeText: "Текст",
            .fileTypeDocument: "Документ",
            .fileTypePDF: "PDF",
            .fileTypeVideo: "Видео",
            .fileTypeAudio: "Аудио",
            .fileTypeArchive: "Архив",
            .fileTypeURL: "URL",
            .fileTypeCode: "Код",
            .fileTypeOther: "Файл",
            .helpSettings: "Настройки ShotCast",
            .helpClose: "Закрыть ShotCast",
            .settingsBehavior: "Поведение",
            .settingsBehaviorDescription: "Настроить поведение приложения",
            .settingsAutoShowDescription: "Приложение будет автоматически показываться при копировании",
            .settingsLaunchAtLoginDescription: "ShotCast будет автоматически запускаться при входе",
            .settingsAutoHide: "Автоскрытие",
            .settingsAutoHideDescription: "Приложение будет автоматически скрываться через определённое время",
            .settingsHideDelay: "Задержка Скрытия",
            .settingsResetDefaults: "Сбросить к Настройкам по Умолчанию",
            .itemLimitTen: "Последние 10 Снимков",
            .itemLimitHundred: "Последние 100 Снимков",
            .itemLimitUnlimited: "Неограниченно",
            .sourceLabel: "Источник",
            .ocrFast: "Быстро",
            .ocrBalanced: "Сбалансированно",
            .ocrAccurate: "Точно",
            .ocrError: "Ошибка OCR",
            .ocrInvalidImage: "Недействительное Изображение",
            .ocrNoTextFound: "Текст Не Найден",
            .ocrCancelled: "OCR Отменено"
        ],
        .chinese: [
            .appName: "ShotCast",
            .menuOpen: "打开 ShotCast",
            .menuSettings: "设置...",
            .menuQuit: "退出",
            .settingsTitle: "ShotCast 设置",
            .settingsGeneral: "通用",
            .settingsAppearance: "外观",
            .settingsAdvanced: "高级",
            .settingsLanguage: "语言",
            .settingsTheme: "主题",
            .settingsMaxItems: "最大项目数",
            .settingsBarHeight: "栏高度",
            .settingsBarOpacity: "透明度",
            .settingsCornerRadius: "圆角半径",
            .settingsItemSpacing: "项目间距",
            .settingsAutoShow: "自动显示",
            .settingsLaunchAtLogin: "登录时启动",
            .themeSystem: "系统",
            .themeLight: "浅色",
            .themeDark: "深色",
            .copied: "已复制！",
            .copyText: "文本已复制到剪贴板",
            .emptyClipboard: "剪贴板中无内容",
            .contextCopy: "复制",
            .contextFavorite: "添加到收藏夹",
            .contextUnfavorite: "从收藏夹移除",
            .contextSaveAsFile: "另存为文件...",
            .contextDelete: "删除",
            .ocrExtract: "使用 OCR 提取文本",
            .ocrSuccess: "OCR 文本已提取",
            .fileTypeImage: "图像",
            .fileTypeText: "文本",
            .fileTypeDocument: "文档",
            .fileTypePDF: "PDF",
            .fileTypeVideo: "视频",
            .fileTypeAudio: "音频",
            .fileTypeArchive: "归档",
            .fileTypeURL: "URL",
            .fileTypeCode: "代码",
            .fileTypeOther: "文件",
            .helpSettings: "ShotCast 设置",
            .helpClose: "关闭 ShotCast",
            .settingsBehavior: "行为",
            .settingsBehaviorDescription: "自定义应用行为",
            .settingsAutoShowDescription: "复制内容时应用会自动显示",
            .settingsLaunchAtLoginDescription: "ShotCast 将在登录时自动启动",
            .settingsAutoHide: "自动隐藏",
            .settingsAutoHideDescription: "应用将在一定时间后自动隐藏",
            .settingsHideDelay: "隐藏延迟",
            .settingsResetDefaults: "重置为默认设置",
            .itemLimitTen: "最近10个截图",
            .itemLimitHundred: "最近100个截图",
            .itemLimitUnlimited: "无限制",
            .sourceLabel: "来源",
            .ocrFast: "快速",
            .ocrBalanced: "平衡",
            .ocrAccurate: "精确",
            .ocrError: "OCR错误",
            .ocrInvalidImage: "无效图像",
            .ocrNoTextFound: "未找到文本",
            .ocrCancelled: "OCR已取消"
        ],
        .japanese: [
            .appName: "ShotCast",
            .menuOpen: "ShotCast を開く",
            .menuSettings: "設定...",
            .menuQuit: "終了",
            .settingsTitle: "ShotCast 設定",
            .settingsGeneral: "一般",
            .settingsAppearance: "外観",
            .settingsAdvanced: "詳細",
            .settingsLanguage: "言語",
            .settingsTheme: "テーマ",
            .settingsMaxItems: "最大アイテム数",
            .settingsBarHeight: "バーの高さ",
            .settingsBarOpacity: "不透明度",
            .settingsCornerRadius: "角の半径",
            .settingsItemSpacing: "アイテム間隔",
            .settingsAutoShow: "自動表示",
            .settingsLaunchAtLogin: "ログイン時に起動",
            .themeSystem: "システム",
            .themeLight: "ライト",
            .themeDark: "ダーク",
            .copied: "コピーしました！",
            .copyText: "テキストがクリップボードにコピーされました",
            .emptyClipboard: "クリップボードに内容がありません",
            .contextCopy: "コピー",
            .contextFavorite: "お気に入りに追加",
            .contextUnfavorite: "お気に入りから削除",
            .contextSaveAsFile: "ファイルとして保存...",
            .contextDelete: "削除",
            .ocrExtract: "OCR でテキストを抽出",
            .ocrSuccess: "OCR テキストが抽出されました",
            .fileTypeImage: "画像",
            .fileTypeText: "テキスト",
            .fileTypeDocument: "文書",
            .fileTypePDF: "PDF",
            .fileTypeVideo: "ビデオ",
            .fileTypeAudio: "オーディオ",
            .fileTypeArchive: "アーカイブ",
            .fileTypeURL: "URL",
            .fileTypeCode: "コード",
            .fileTypeOther: "ファイル",
            .helpSettings: "ShotCast 設定",
            .helpClose: "ShotCast を閉じる",
            .settingsBehavior: "動作",
            .settingsBehaviorDescription: "アプリの動作をカスタマイズ",
            .settingsAutoShowDescription: "何かがコピーされたときにアプリが自動的に表示されます",
            .settingsLaunchAtLoginDescription: "ShotCast はログイン時に自動的に開始されます",
            .settingsAutoHide: "自動非表示",
            .settingsAutoHideDescription: "アプリは一定時間後に自動的に非表示になります",
            .settingsHideDelay: "非表示遅延",
            .settingsResetDefaults: "デフォルトにリセット",
            .itemLimitTen: "最新の10ショット",
            .itemLimitHundred: "最新の100ショット",
            .itemLimitUnlimited: "制限なし",
            .sourceLabel: "ソース",
            .ocrFast: "高速",
            .ocrBalanced: "バランス",
            .ocrAccurate: "正確",
            .ocrError: "OCRエラー",
            .ocrInvalidImage: "無効な画像",
            .ocrNoTextFound: "テキストが見つかりません",
            .ocrCancelled: "OCRがキャンセルされました"
        ],
        .korean: [
            .appName: "ShotCast",
            .menuOpen: "ShotCast 열기",
            .menuSettings: "설정...",
            .menuQuit: "종료",
            .settingsTitle: "ShotCast 설정",
            .settingsGeneral: "일반",
            .settingsAppearance: "모양",
            .settingsAdvanced: "고급",
            .settingsLanguage: "언어",
            .settingsTheme: "테마",
            .settingsMaxItems: "최대 항목 수",
            .settingsBarHeight: "바 높이",
            .settingsBarOpacity: "투명도",
            .settingsCornerRadius: "모서리 반지름",
            .settingsItemSpacing: "항목 간격",
            .settingsAutoShow: "자동 표시",
            .settingsLaunchAtLogin: "로그인 시 시작",
            .themeSystem: "시스템",
            .themeLight: "밝게",
            .themeDark: "어둡게",
            .copied: "복사됨!",
            .copyText: "텍스트가 클립보드에 복사됨",
            .emptyClipboard: "클립보드에 내용 없음",
            .contextCopy: "복사",
            .contextFavorite: "즐겨찾기에 추가",
            .contextUnfavorite: "즐겨찾기에서 제거",
            .contextSaveAsFile: "파일로 저장...",
            .contextDelete: "삭제",
            .ocrExtract: "OCR로 텍스트 추출",
            .ocrSuccess: "OCR 텍스트 추출됨",
            .fileTypeImage: "이미지",
            .fileTypeText: "텍스트",
            .fileTypeDocument: "문서",
            .fileTypePDF: "PDF",
            .fileTypeVideo: "비디오",
            .fileTypeAudio: "오디오",
            .fileTypeArchive: "아카이브",
            .fileTypeURL: "URL",
            .fileTypeCode: "코드",
            .fileTypeOther: "파일",
            .helpSettings: "ShotCast 설정",
            .helpClose: "ShotCast 닫기",
            .settingsBehavior: "동작",
            .settingsBehaviorDescription: "앱 동작 사용자 정의",
            .settingsAutoShowDescription: "무언가 복사될 때 앱이 자동으로 표시됩니다",
            .settingsLaunchAtLoginDescription: "ShotCast가 로그인 시 자동으로 시작됩니다",
            .settingsAutoHide: "자동 숨기기",
            .settingsAutoHideDescription: "앱이 일정 시간 후 자동으로 숨겨집니다",
            .settingsHideDelay: "숨김 지연",
            .settingsResetDefaults: "기본값으로 재설정",
            .itemLimitTen: "최근 10개 샷",
            .itemLimitHundred: "최근 100개 샷",
            .itemLimitUnlimited: "무제한",
            .sourceLabel: "소스",
            .ocrFast: "빠름",
            .ocrBalanced: "균형",
            .ocrAccurate: "정확",
            .ocrError: "OCR 오류",
            .ocrInvalidImage: "잘못된 이미지",
            .ocrNoTextFound: "텍스트를 찾을 수 없음",
            .ocrCancelled: "OCR 취소됨"
        ],
        .arabic: [
            .appName: "ShotCast",
            .menuOpen: "فتح ShotCast",
            .menuSettings: "الإعدادات...",
            .menuQuit: "خروج",
            .settingsTitle: "إعدادات ShotCast",
            .settingsGeneral: "عام",
            .settingsAppearance: "المظهر",
            .settingsAdvanced: "متقدم",
            .settingsLanguage: "اللغة",
            .settingsTheme: "السمة",
            .settingsMaxItems: "الحد الأقصى للعناصر",
            .settingsBarHeight: "ارتفاع الشريط",
            .settingsBarOpacity: "الشفافية",
            .settingsCornerRadius: "نصف قطر الزاوية",
            .settingsItemSpacing: "تباعد العناصر",
            .settingsAutoShow: "إظهار تلقائي",
            .settingsLaunchAtLogin: "التشغيل عند الدخول",
            .themeSystem: "النظام",
            .themeLight: "فاتح",
            .themeDark: "داكن",
            .copied: "تم النسخ!",
            .copyText: "تم نسخ النص إلى الحافظة",
            .emptyClipboard: "لا يوجد محتوى في الحافظة",
            .contextCopy: "نسخ",
            .contextFavorite: "إضافة إلى المفضلة",
            .contextUnfavorite: "إزالة من المفضلة",
            .contextSaveAsFile: "حفظ كملف...",
            .contextDelete: "حذف",
            .ocrExtract: "استخراج النص بـ OCR",
            .ocrSuccess: "تم استخراج نص OCR",
            .fileTypeImage: "صورة",
            .fileTypeText: "نص",
            .fileTypeDocument: "وثيقة",
            .fileTypePDF: "PDF",
            .fileTypeVideo: "فيديو",
            .fileTypeAudio: "صوت",
            .fileTypeArchive: "أرشيف",
            .fileTypeURL: "رابط",
            .fileTypeCode: "كود",
            .fileTypeOther: "ملف",
            .helpSettings: "إعدادات ShotCast",
            .helpClose: "إغلاق ShotCast",
            .settingsBehavior: "السلوك",
            .settingsBehaviorDescription: "تخصيص سلوك التطبيق",
            .settingsAutoShowDescription: "سيظهر التطبيق تلقائياً عند نسخ شيء ما",
            .settingsLaunchAtLoginDescription: "ShotCast سيبدأ تلقائياً عند الدخول",
            .settingsAutoHide: "الإخفاء التلقائي",
            .settingsAutoHideDescription: "سيختفي التطبيق تلقائياً بعد وقت معين",
            .settingsHideDelay: "تأخير الإخفاء",
            .settingsResetDefaults: "إعادة تعيين الافتراضات",
            .itemLimitTen: "آخر 10 لقطات",
            .itemLimitHundred: "آخر 100 لقطة",
            .itemLimitUnlimited: "غير محدود",
            .sourceLabel: "المصدر",
            .ocrFast: "سريع",
            .ocrBalanced: "متوازن",
            .ocrAccurate: "دقيق",
            .ocrError: "خطأ في OCR",
            .ocrInvalidImage: "صورة غير صالحة",
            .ocrNoTextFound: "لم يتم العثور على نص",
            .ocrCancelled: "تم إلغاء OCR"
        ]
    ]
}

enum LocalizationKey: String {
    case appName = "appName"
    case menuOpen = "menuOpen"
    case menuSettings = "menuSettings"
    case menuQuit = "menuQuit"
    case settingsTitle = "settingsTitle"
    case settingsGeneral = "settingsGeneral"
    case settingsAppearance = "settingsAppearance"
    case settingsAdvanced = "settingsAdvanced"
    case settingsLanguage = "settingsLanguage"
    case settingsTheme = "settingsTheme"
    case settingsMaxItems = "settingsMaxItems"
    case settingsBarHeight = "settingsBarHeight"
    case settingsBarOpacity = "settingsBarOpacity"
    case settingsCornerRadius = "settingsCornerRadius"
    case settingsItemSpacing = "settingsItemSpacing"
    case settingsAutoShow = "settingsAutoShow"
    case settingsLaunchAtLogin = "settingsLaunchAtLogin"
    case themeSystem = "themeSystem"
    case themeLight = "themeLight"
    case themeDark = "themeDark"
    case copied = "copied"
    case copyText = "copyText"
    case emptyClipboard = "emptyClipboard"
    case contextCopy = "contextCopy"
    case contextFavorite = "contextFavorite"
    case contextUnfavorite = "contextUnfavorite"
    case contextSaveAsFile = "contextSaveAsFile"
    case contextDelete = "contextDelete"
    case ocrExtract = "ocrExtract"
    case ocrSuccess = "ocrSuccess"
    case fileTypeImage = "fileTypeImage"
    case fileTypeText = "fileTypeText"
    case fileTypeDocument = "fileTypeDocument"
    case fileTypePDF = "fileTypePDF"
    case fileTypeVideo = "fileTypeVideo"
    case fileTypeAudio = "fileTypeAudio"
    case fileTypeArchive = "fileTypeArchive"
    case fileTypeURL = "fileTypeURL"
    case fileTypeCode = "fileTypeCode"
    case fileTypeOther = "fileTypeOther"
    case helpSettings = "helpSettings"
    case helpClose = "helpClose"
    case settingsBehavior = "settingsBehavior"
    case settingsBehaviorDescription = "settingsBehaviorDescription"
    case settingsAutoShowDescription = "settingsAutoShowDescription"
    case settingsLaunchAtLoginDescription = "settingsLaunchAtLoginDescription"
    case settingsAutoHide = "settingsAutoHide"
    case settingsAutoHideDescription = "settingsAutoHideDescription"
    case settingsHideDelay = "settingsHideDelay"
    case settingsResetDefaults = "settingsResetDefaults"
    case itemLimitTen = "itemLimitTen"
    case itemLimitHundred = "itemLimitHundred"
    case itemLimitUnlimited = "itemLimitUnlimited"
    case sourceLabel = "sourceLabel"
    case ocrFast = "ocrFast"
    case ocrBalanced = "ocrBalanced"
    case ocrAccurate = "ocrAccurate"
    case ocrError = "ocrError"
    case ocrInvalidImage = "ocrInvalidImage"
    case ocrNoTextFound = "ocrNoTextFound"
    case ocrCancelled = "ocrCancelled"
}

// MARK: - String Extension for Easy Usage
extension String {
    init(localized key: LocalizationKey) {
        self = LocalizationManager.shared.localizedString(key)
    }
}